title: Urs Hofer
email: cut@automatic-cinema.com
description: >-
  I do some coding: Websites, Installations, Books. Sometimes I teach.
  There will be more on this site some day.
baseurl: ""
host: 0.0.0.0
url: "https://www.urshofer.ch"
source: .